[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = "added description here"
[tool.poetry.dependencies]
pandas = "*"
python = "^3.8"
seaborn = "*"
